### ISSUE TITLE
Error report anki 2.1.54

### ISSUE THREAD

**Issue by feldspar9** [mmaaz-git/anki-pasteOCR#1]
Hi Maaz,

I am a frequent user of your addon PasteOCR. It has saved me a huge amount of time.

Just wanted to let you know about a bug that has been popping up ever since I updated from Anki 2.1.49 to 2.1.54

Below is the error message that appears every time I press the pasteOCR button

Thank you 

---------

Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.15.2 PyQt 5.15.5
Platform: Windows 10
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-08-15 14:45:23

Caught exception:
Traceback (most recent call last):
File "aqt.webview", line 42, in cmd
File "aqt.webview", line 149, in _onCmd
File "aqt.webview", line 624, in _onBridgeCmd
File "decorator", line 232, in fun
File "anki.hooks", line 89, in decorator_wrapper
File "anki.hooks", line 86, in repl
File "C:\Users\AA\AppData\Roaming\Anki2\addons21\24411424\custom_shortcuts.py", line 440, in cs_captureBridgeToggleSticky
return _old(self,cmd)
File "aqt.editor", line 467, in onBridgeCmd
File "C:\Users\AA\AppData\Roaming\Anki2\addons21\1746010116\__init__.py", line 22, in onStrike
output = pytesseract.image_to_string(path).replace("\n", "<br>")
File "C:\Users\AA\AppData\Roaming\Anki2\addons21\1746010116\pytesseract\pytesseract.py", line 368, in image_to_string
return {
File "C:\Users\AA\AppData\Roaming\Anki2\addons21\1746010116\pytesseract\pytesseract.py", line 371, in <lambda>
Output.STRING: lambda: run_and_get_output(*args),
File "C:\Users\AA\AppData\Roaming\Anki2\addons21\1746010116\pytesseract\pytesseract.py", line 280, in run_and_get_output
run_tesseract(**kwargs)
File "C:\Users\AA\AppData\Roaming\Anki2\addons21\1746010116\pytesseract\pytesseract.py", line 257, in run_tesseract
raise TesseractError(proc.returncode, get_errors(error_string))
1746010116.pytesseract.pytesseract.TesseractError: (1, 'Tesseract Open Source OCR Engine v5.0.0-alpha.20200328 with Leptonica Error, cannot read input file C:\\Program Files\\Anki\\ocrtmp.png: No such file or directory Error during processing.')

**Comment by mmngtb** [comment]
Mine is also doing the same:

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.15.2 PyQt 5.15.5
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-12-12 22:07:59

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 42, in cmd
  File "aqt.webview", line 149, in _onCmd
  File "aqt.webview", line 624, in _onBridgeCmd
  File "aqt.editor", line 467, in onBridgeCmd
  File "C:\Users\Michael Lopez\AppData\Roaming\Anki2\addons21\1746010116\__init__.py", line 22, in onStrike
    output = pytesseract.image_to_string(path).replace("\n", "<br>")
  File "C:\Users\Michael Lopez\AppData\Roaming\Anki2\addons21\1746010116\pytesseract\pytesseract.py", line 368, in image_to_string
    return {
  File "C:\Users\Michael Lopez\AppData\Roaming\Anki2\addons21\1746010116\pytesseract\pytesseract.py", line 371, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
  File "C:\Users\Michael Lopez\AppData\Roaming\Anki2\addons21\1746010116\pytesseract\pytesseract.py", line 280, in run_and_get_output
    run_tesseract(**kwargs)
  File "C:\Users\Michael Lopez\AppData\Roaming\Anki2\addons21\1746010116\pytesseract\pytesseract.py", line 257, in run_tesseract
    raise TesseractError(proc.returncode, get_errors(error_string))
1746010116.pytesseract.pytesseract.TesseractError: (1, 'Tesseract Open Source OCR Engine v5.0.0-alpha.20200328 with Leptonica Error, cannot read input file C:\\Program Files\\Anki\\ocrtmp.png: No such file or directory Error during processing.')

**Comment by udobehm** [comment]
Will there be an update for the new (Qt6) version of Anki?

**Comment by mmaaz-git** [comment]
Hi all, thank you for letting me know! I just updated it, it should work with the new Qt6. Can you try updating it and letting me know if it doesn't work?

Apologies for the late reply, I have been swamped with school. And thank you for the kind words :) glad you find it useful.

**Comment by udobehm** [comment]
Hi, working now - thanks!

Is there any way to change the language of the OCR engine?

**Comment by mmaaz-git** [comment]
Great! 

I think it is possible to download other language files for the Tesseract engine but the code for the plug-in itself currently only supports English. I can look into how to make it flexible to use other languages for the future. Appreciate the feedback!

**Comment by udobehm** [comment]
Hi,

may I know whether you’ve made any progress in integrating language files into your Anki plugin?

Thanks!
Udo

Von: Maaz ***@***.***>
Gesendet: Dienstag, 28. Februar 2023 00:29
An: mmaaz-git/anki-pasteOCR ***@***.***>
Cc: udobehm ***@***.***>; Comment ***@***.***>
Betreff: Re: [mmaaz-git/anki-pasteOCR] Error report anki 2.1.54 (Issue #1)


Great!

I think it is possible to download other language files for the Tesseract engine but the code for the plug-in itself currently only supports English. I can look into how to make it flexible to use other languages for the future. Appreciate the feedback!
